stages: 
  - realise
  - deploy
  - notify

variables:
  VERSION: 1.0.${CI_PIPELINE_ID} # добавил перменную версия

chart-realise:
  stage: realise
  only:
    changes: 
    - backend-chart/**/* #триггер для запуска пайплайна - изменения в директории kubernetes (рекурссивно)
  image: alpine/helm:3.13.2
  script:   
    - ls
    - helm package backend-chart --version ${VERSION}
    - ls
    - curl -u std-024-12:E5h3x9Xk https://nexus.praktikum-services.tech/repository/dumplings_store_nikolaev/ --upload-file backend-${VERSION}.tgz



chart-deploy:
  stage: deploy
  only:
    changes: 
    - backend-chart/**/* #триггер для запуска пайплайна - изменения в директории kubernetes (рекурссивно)
  image: alpine/helm:3.13.2
  before_script:
    - mkdir -p ~/.kube/
    - echo $kubeconfig
    - echo "$kubeconfig" >> ~/.kube/config #создаем конфиг куба из меременной гитлаба
    - echo $kube_cert >> ~/.kube/ca.pem
    - chmod -R 700 ~/.kube
    - cat ~/.kube/config
  script:   
    - ls 
    - helm upgrade --atomic --install backend-chart https://nexus.praktikum-services.tech/repository/dumplings_store_nikolaev/backend-chart-${VERSION}.tgz
    - sleep 30
    - helm list
    - kubectl get all 

telegram-notification-backend: #задача с именем telegram-notification-backend
  variables:
      TEXT: "Андрей Николаев собрал helm chart backend-chart ${CI_PROJECT_URL}/-/jobs/${PREV_JOB_ID}/artifacts/download" #обьявление перменных, где ci_project_url - урл проекта, prev_job_id - переменная, обявленная в джобе build-backend-code-job и сохраненная в {CI_PROJECT_DIR}/build.env
      TLGRM: "https://api.telegram.org/bot5933756043:AAE8JLL5KIzgrNBeTP5e-1bkbJy4YRoeGjs/sendMessage"
  stage: notify #этап уведомлений
  only:
    changes:
    - backend-chart/**/* #только для изменений в директории backend
    variables: #РАСКОМЕНТИТЬ НЕ ЗАБУДЬ ЭТУ СТРОКУ И СЛЕДУЮЩУЮ!!!!!!!!!!!!
    - $CI_COMMIT_MESSAGE =~ /send notification/ # только для изменений содержащих в сообщении коммита "send notification"
  script:
     # - echo "The BACK_CI_JOB_ID is ${CI_PROJECT_DIR}" - проверки, при помощи которых опредлял CI_PROJECT_DIR
     # - echo "The BACK_CI_JOB_ID is $PREV_JOB_ID" - проверки, при помощи которых я определял, что записано в переменную prev_job_id
      - 'curl -X POST -H "Content-type: application/json" --data "{\"chat_id\": \"-1002134018008\", \"text\": \"${TEXT}\" }" ${TLGRM}' #отправка курлом сообщения методом post
     # - ls -lah - дополнительные проверки
     # - pwd - дополнительные проверки


