stages: 
  - realise
  - deploy
  - notification

variables:
  VERSION: 1.0.${CI_PIPELINE_ID} # добавил перменную версия

chart-realise:
  stage: realise
  # only:
  #   changes: 
#    - backend-chart/**/* #триггер для запуска пайплайна - изменения в директории kubernetes (рекурссивно)
  image: alpine/helm:3.13.2
  script:   
    - ls
    - helm package backend --version ${VERSION}
    - ls
    # - curl -u std-024-12:E5h3x9Xk https://nexus.praktikum-services.tech/repository/dumplings_store_nikolaev/ --upload-file dumpling-store-${VERSION}.tgz



# chart-deploy:
#   stage: deploy
# #   only:
# #     changes: 
# # #    - kubernetes/**/* #триггер для запуска пайплайна - изменения в директории kubernetes (рекурссивно)
#   image: alpine/helm:3.13.2
#   before_script:
#     - mkdir -p ~/.kube/
#     - echo "$kubeconfig" >> ~/.kube/config #создаем конфиг куба из меременной гитлаба
#     - chmod -R 700 ~/.kube
#   script:   
#     - ls 
#     - helm install dumpling-store https://nexus.praktikum-services.tech/repository/dumplings_store_nikolaev/dumpling-store-${VERSION}.tgz


