backend:
  app: backend
  port: 8081
  service: 
    type: ClusterIP
    port: 8081
    protocol: TCP
    targetPort: 8081

  deployment :
    replicas: 1
    revisionHistoryLimit: 15
    maxUnavailable: 1 #максимальное количество одновременно неработающих Pod'ов в процессе обновления
    maxSurge: 20%
    image: gitlab.praktikum-services.ru:5050/std-024-12/dumplings-store/dumpling-backend
    tag: latest
    imagePullPolicy: Always # image извлекается всегда
    containerPort: 8081
    livenessProbe_path: /health
    livenessProbe_port: 8081
    initialDelaySeconds: 15
    periodSeconds: 30
    timeoutSeconds: 1
    failureThreshold: 6

  VPA:
    updateMode: "Auto"
#    containerName: "*"
    minAllowed:
      cpu: 0m
      memory: 0Mi
    maxAllowed:
      cpu: 1
      memory: 500Mi
    controlledResources: ["cpu", "memory"]
    controlledValues: RequestsAndLimits
