include:
  - template: Security/SAST.gitlab-ci.yml 

stages: 
  - build  #сборка
  - test #test
  - release
  - notify  #уведомление1


variables:
  VERSION: 1.0.${CI_PIPELINE_ID} # добавил перменную версия


build-backend-code-job: #задача с именем build-backend-code-job
  stage: build
  rules:
    - changes: 
      - backend/* #только для изменений в директории backend
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  # переменные CI_REGISTRY_USER, CI_REGISTRY_PASSWORD, CI_REGISTRY генерятся Гитлабом, их задавать не надо
  script: 
    - echo "test"
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/backend"
      --dockerfile "${CI_PROJECT_DIR}/backend/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/dumpling-backend:$CI_COMMIT_SHA"
      --build-arg VERSION=$VERSION
      --cache=true
    - echo "$CI_REGISTRY_IMAGE"


backend-test:  #задача с именем backend-test
  image: golang:1.16-alpine
  stage: test
  script:
    - cd backend
    - CGO_ENABLED=0 go test -v ./... 
  needs: 
    - build-backend-code-job
    

sonarqube-backend-sast:
  stage: test
  image: sonarsource/sonar-scanner-cli:latest #образ
  script:
    - cd backend
    - sonar-scanner
      -Dsonar.projectName=${SONAR_PROJECT_NAME_BACKEND} 
      -Dsonar.host.url=${SONARQUBE_URLBACKEND} 
      -Dsonar.login=${SONAR_LOGIN_BACKEND}
      -Dsonar.projectKey=${SONAR_PROJECT_KEY_BACKEND}
      -Dsonar.qualitygate.wait=true #параметры
  needs:
    - build-backend-code-job


release:
  variables:
    GIT_STRATEGY: none
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [ "" ]
  cache: [ ]
  stage: release
  before_script:
    - crane auth login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - crane tag $CI_REGISTRY_IMAGE/dumpling-backend:$CI_COMMIT_SHA latest
  needs:
    - build-backend-code-job


telegram-notification-backend: #задача с именем telegram-notification-backend
  variables:
      TEXT: "Андрей Николаев собрал backend ${CI_PROJECT_URL}/-/jobs/${PREV_JOB_ID}/artifacts/download" #обьявление перменных, где ci_project_url - урл проекта, prev_job_id - переменная, обявленная в джобе build-backend-code-job и сохраненная в {CI_PROJECT_DIR}/build.env
      TLGRM: "https://api.telegram.org/bot5933756043:AAE8JLL5KIzgrNBeTP5e-1bkbJy4YRoeGjs/sendMessage"
  stage: notify #этап уведомлений
  only:
    changes:
    - backend/* #только для изменений в директории backend
    variables: #РАСКОМЕНТИТЬ НЕ ЗАБУДЬ ЭТУ СТРОКУ И СЛЕДУЮЩУЮ!!!!!!!!!!!!
    - $CI_COMMIT_MESSAGE =~ /send notification/ # только для изменений содержащих в сообщении коммита "send notification"
  script:
    - 'curl -X POST -H "Content-type: application/json" --data "{\"chat_id\": \"-1002134018008\", \"text\": \"${TEXT}\" }" ${TLGRM}' #отправка курлом сообщения методом post
  needs:
    - build-backend-code-job # прописываем зависимость от джоба с именем build-backend-code-job
#добавил изменения для проверки


