apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  annotations:
    kubernetes.io/ingress.class: {{  .Values.frontend.ingress.ingressClassName  }}
    cert-manager.io/cluster-issuer: {{  .Values.frontend.ingress.cluster-issuer  }}
spec:
  tls:
    - hosts:
      - {{  .Values.frontend.ingress.host  }}
      secretName: {{  .Values.frontend.ingress.secretName  }}
  rules:
    - host: {{  .Values.frontend.ingress.host  }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Chart.Name }}
              port:
                number: {{  .Values.frontend.ingress.service_port_number  }}
